const DISABLED_BUTTON_OPACITY = 0.8;
const IMAGE_TRANSITION_MS_SLOW = 800;
const IMAGE_TRANSITION_MS_FAST = 200;

export {
  DISABLED_BUTTON_OPACITY,
  IMAGE_TRANSITION_MS_FAST,
  IMAGE_TRANSITION_MS_SLOW,
};
